version: "3.1"

services:
  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: horizon_backend
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier

  database:
    image: horizon_database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
